image: williamyeh/ansible:centos7

test:
  script:
    - if [ -f 'requirements.yml' ]; then yum -y install git && ansible-galaxy install -r requirements.yml; fi
    - ansible-playbook test.yml -c local -vvv -b
    # - ./test/checks.sh # tasks have their own asserts, but this is an option too
